version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    
